import Head from 'next/head';
import styles from '../styles/Home.module.css'
import Login from '../components/Login';
import UploadImage from '../components/uploadimage';
import KevsPics from '../components/kevspics';




export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id='login'>
        <Login />
      </div>
      <div id='upload' style={{ display: 'none'}}>
        <UploadImage />
      </div>
      <div id='pics' style={{ display: 'none' }}>
        <KevsPics />
      </div>
      
      
    </div>
  )
}
