name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          pwd
          cd kevs_gopro_app/
          ls
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn build
          mv out/kevspics.html out/kevspics
          mv out/uploadimage.html out/uploadimage

