name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          pwd
          cd kevs_gopro_app/
          ls
      - run: ls
      - run: cd kevs_gopro_app/
      - run: ls
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: mv out/kevspics.html out/kevspics
      - run: mv out/uploadimage.html out/uploadimage
